- hosts: database-servers
  become: true
  tasks:

    - name: Update the apt cache
      apt:
        update_cache: true

    - name: Install PostgreSQL and required packages
      apt:
        name:
          - postgresql
          - postgresql-contrib
          - python3-pip
          - python3-psycopg2
          - acl
        state: present
        update_cache: yes

    - name: Start PostgreSQL service
      systemd:
        name: postgresql
        state: started
        enabled: true

    - name: Configure PostgreSQL to listen to all addresses
      lineinfile:
        path: /etc/postgresql/16/main/postgresql.conf
        regexp: '^#listen_addresses ='
        line: "listen_addresses = '*'"
        state: present

    - name: Allow remote connections to the database
      lineinfile:
        path: /etc/postgresql/16/main/pg_hba.conf
        insertafter: '^# IPv4 local connections:'
        line: "host    all             all             0.0.0.0/0               md5"
        state: present

    - name: Change postgres user password
      become: yes
      become_method: sudo
      become_user: postgres
      postgresql_user:
        name: postgres
        password: "postgres"

    - name: Create the database
      become: yes
      become_method: sudo
      become_user: postgres
      postgresql_db:
        name: mydb
        login_user: "postgres"
        login_password: "postgres"